<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_rZ0U0HOuEe2vxNtY-8h9rA" name="PremiumEmployment" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_rZ0U0XOuEe2vxNtY-8h9rA" name="Premium Employment" displayName="Premium Employment">
      <elements xmi:type="process:Lane" xmi:id="_rZ0U0nOuEe2vxNtY-8h9rA" name="Candidate lane" actor="__4bHAHOuEe2vxNtY-8h9rA">
        <elements xmi:type="process:StartEvent" xmi:id="_rZ0U03OuEe2vxNtY-8h9rA" name="Start1" outgoing="_rZ0U6HOuEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rZ0U1HOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rZ0U1XOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rZ0U1nOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_rZ0U13OuEe2vxNtY-8h9rA" name="Accept Terms And Conditions" outgoing="_cCYbUHOvEe2vxNtY-8h9rA" incoming="_rZ0U6HOuEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rZ0U2HOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rZ0U2XOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rZ0U2nOuEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_46rVgIU4Ee2xlJGGUNPD4A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_46rVgYU4Ee2xlJGGUNPD4A" name="areTermsAccepted" content="areTermsAccepted" type="TYPE_VARIABLE" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:Data" xmi:id="_Y_IwgIU5Ee2xlJGGUNPD4A" name="areTermsAccepted" dataType="_rZ0U_HOuEe2vxNtY-8h9rA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_46rVgoU4Ee2xlJGGUNPD4A" name="termsAccepted()" content="areTermsAndConditionsAccepted" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ZjhP8IU5Ee2xlJGGUNPD4A" name="areTermsAndConditionsAccepted" type="BOOLEAN">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_ZjhP8YU5Ee2xlJGGUNPD4A"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_46rVg4U4Ee2xlJGGUNPD4A" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_rZ0U23OuEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_rZ0U3HOuEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_rZ0U3XOuEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_rZ0U3nOuEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_rZ0U33OuEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_rZ0U4HOuEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_pQ0kYIU7Ee2xlJGGUNPD4A" name="AcceptTermsForm" content="2a685967-0fe0-42c7-9a80-022952c55be4" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_rZ0U4nOuEe2vxNtY-8h9rA">
            <inputs xmi:type="process:ContractInput" xmi:id="_sVldQIU4Ee2xlJGGUNPD4A" name="areTermsAndConditionsAccepted" type="BOOLEAN">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_sVldQYU4Ee2xlJGGUNPD4A"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_rZ0U43OuEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dUu0AHOvEe2vxNtY-8h9rA" name="TermsDecision" outgoing="_k-mvcHOvEe2vxNtY-8h9rA _mSeLEHOvEe2vxNtY-8h9rA" incoming="_cCYbUHOvEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cCAA0XOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cCAA0HOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cCAA0nOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_k-fasHOvEe2vxNtY-8h9rA" name="End1" incoming="_k-mvcHOvEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_k-gBwXOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_k-gBwHOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_k-gBwnOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_AAH1AHOwEe2vxNtY-8h9rA" name="Pay Premium Employment Services" outgoing="_PjrCcHOwEe2vxNtY-8h9rA" incoming="_mSeLEHOvEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_mSWPQXOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_mSWPQHOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_mSWPQnOvEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_mSWPQ3OvEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_mSWPRHOvEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_mSWPRXOvEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_mSWPR3OvEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_mSWPRnOvEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_AAIcGXOwEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_--X9UIU4Ee2xlJGGUNPD4A" name="PayPremiumEmploymentForm" content="c1787958-983e-4eee-8b06-8fcda8507391" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_AAIcGHOwEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_AAIcG3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_k-KOEHOwEe2vxNtY-8h9rA" name="Send email about premium employment process " outgoing="_xBZWcHOwEe2vxNtY-8h9rA" incoming="_XuXkQHO2Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_k-KOEnOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_k-KOEXOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_k-KOE3OwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_k-KOFHOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_k-KOFXOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_k-KOFnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_k-KOGHOwEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_k-KOF3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_zAT6MHOwEe2vxNtY-8h9rA" name="Improve CV and cover letter" outgoing="_35z_wHOwEe2vxNtY-8h9rA" incoming="_xBZWcHOwEe2vxNtY-8h9rA _BsmvgHOxEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xBT24nOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xBT24XOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xBT243OwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xBT25HOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xBT25XOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xBT25nOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xBT26HOwEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xBT253OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zAT6OnOwEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhwIVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zAT6OXOwEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zAT6PHOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Bsc-gHOxEe2vxNtY-8h9rA" name="ApproveCVAndCoverLetter" outgoing="_BsmvgHOxEe2vxNtY-8h9rA _A_y3YHOyEe2vxNtY-8h9rA" incoming="_61r7AHOwEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Bsc-gnOxEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Bsc-gXOxEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BsdlkHOxEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_0yh-YHOzEe2vxNtY-8h9rA" name="AcceptDates" outgoing="_y0SJAHOzEe2vxNtY-8h9rA _8JVz4HOzEe2vxNtY-8h9rA" incoming="_oaqp0HOzEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oam_cnOzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oam_cXOzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oam_c3OzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_KWPXcHO0Ee2vxNtY-8h9rA" name="Choose date" outgoing="_1v1esHO0Ee2vxNtY-8h9rA" incoming="_KDT0YHO0Ee2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KDQxEXO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KDQxEHO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KDQxEnO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_KDQxE3O0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_KDQxFHO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_KDQxFXO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_KDQxF3O0Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_KDQxFnO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_KWPXenO0Ee2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhwYVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_KWPXeXO0Ee2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_KWPXfHO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_7hmpAHO0Ee2vxNtY-8h9rA" name="ChosenDate" outgoing="__k108HO0Ee2vxNtY-8h9rA _nM3IAHO1Ee2vxNtY-8h9rA" incoming="_1v1esHO0Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1vx0UnO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1vx0UXO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1vx0U3O0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="__kwVYHO0Ee2vxNtY-8h9rA" name="Send cancellation email to company HR employee " outgoing="_ruUhAHO1Ee2vxNtY-8h9rA" incoming="_A3K_gHO1Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__kwVYnO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__kwVYXO0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__kwVY3O0Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="__kwVZHO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="__kwVZXO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="__kwVZnO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="__kwVaHO0Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="__kwVZ3O0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_A3E44HO1Ee2vxNtY-8h9rA" name="Gateway1" outgoing="_A3K_gHO1Ee2vxNtY-8h9rA _CxjBgHO1Ee2vxNtY-8h9rA" incoming="__k108HO0Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A3E44nO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A3E44XO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A3E443O1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_ruQ2oHO1Ee2vxNtY-8h9rA" name="Merge2" outgoing="_syHq4HO2Ee2vxNtY-8h9rA" incoming="_ruUhAHO1Ee2vxNtY-8h9rA _sLlr0HO1Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ruQ2onO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ruQ2oXO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ruQ2o3O1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_aGAxEHO2Ee2vxNtY-8h9rA" name="RejctedInterview" outgoing="_aGHewHO2Ee2vxNtY-8h9rA" incoming="_A_y3YHOyEe2vxNtY-8h9rA _gv85gHO2Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aGAxEnO2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aGAxEXO2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aGAxE3O2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_sKo0IHO2Ee2vxNtY-8h9rA" name="InterviewDecision" outgoing="_gv85gHO2Ee2vxNtY-8h9rA _HUJ_IHO3Ee2vxNtY-8h9rA" incoming="_syHq4HO2Ee2vxNtY-8h9rA _wN54cHO6Ee2vxNtY-8h9rA _5LkXAHO6Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sKpbMXO2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sKpbMHO2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sKpbMnO2Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_HUFGoHO3Ee2vxNtY-8h9rA" name="End2" incoming="_HUJ_IHO3Ee2vxNtY-8h9rA _NhfjwHO6Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HUFtsXO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HUFtsHO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HUFtsnO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_gqki4HO5Ee2vxNtY-8h9rA" name="Send cancellation email to Premium Department employee " outgoing="_sLlr0HO1Ee2vxNtY-8h9rA" incoming="_CxjBgHO1Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_CxglQXO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CxglQHO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_CxglQnO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_CxglQ3O1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_CxglRHO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_CxglRXO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_CxglR3O1Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_CxglRnO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_h3HOgHO5Ee2vxNtY-8h9rA" name="Send email about chosen dates" outgoing="_KDT0YHO0Ee2vxNtY-8h9rA" incoming="_8JVz4HOzEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8JQ7YXOzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8JQ7YHOzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8JQ7YnOzEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8JQ7Y3OzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8JQ7ZHOzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8JQ7ZXOzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8JQ7Z3OzEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8JQ7ZnOzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_5LX_MHO5Ee2vxNtY-8h9rA" name="Send email about interview" outgoing="_A8-6UHO6Ee2vxNtY-8h9rA" incoming="_L2yVcHO6Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5LYmQXO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5LYmQHO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5LYmQnO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5LYmQ3O5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5LYmRHO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5LYmRXO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5LYmR3O5Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5LYmRnO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_Nhb5YHO6Ee2vxNtY-8h9rA" name="FinalDecision" outgoing="_NhfjwHO6Ee2vxNtY-8h9rA _wN54cHO6Ee2vxNtY-8h9rA" incoming="_A8-6UHO6Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_NhcgcHO6Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Nhb5YXO6Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_NhcgcXO6Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_xjWtMIU5Ee2xlJGGUNPD4A" name="Set process initiator" outgoing="_xj9KIIU5Ee2xlJGGUNPD4A" incoming="_PjrCcHOwEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xjcz0YU5Ee2xlJGGUNPD4A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xjcz0IU5Ee2xlJGGUNPD4A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xjda4IU5Ee2xlJGGUNPD4A" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xjda4YU5Ee2xlJGGUNPD4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xjda4oU5Ee2xlJGGUNPD4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xjda44U5Ee2xlJGGUNPD4A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xjda5YU5Ee2xlJGGUNPD4A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xjda5IU5Ee2xlJGGUNPD4A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_5Bdt4HO8Ee2vxNtY-8h9rA" name="Interviewers Lane" actor="_xlymgHO8Ee2vxNtY-8h9rA">
        <elements xmi:type="process:Task" xmi:id="_ovaYgHO4Ee2vxNtY-8h9rA" name="Fill Interview Review" outgoing="_YkKR4HO4Ee2vxNtY-8h9rA" incoming="_nM3IAHO1Ee2vxNtY-8h9rA" type="PARALLEL" collectionDataToMultiInstantiate="_MfIZwHO4Ee2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_J_WIIHO5Ee2vxNtY-8h9rA" source="_J_GQgHO5Ee2vxNtY-8h9rA"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nMyPgnO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nMyPgXO1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nMyPg3O1Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_nMy2kHO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_nMy2kXO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_nMy2knO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_nMy2lHO1Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_nMy2k3O1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ovaYinO4Ee2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhwoVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ovaYiXO4Ee2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ovaYjHO4Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_ceq_oHO4Ee2vxNtY-8h9rA" name="InterviewersDecision" outgoing="_dfu-kHO5Ee2vxNtY-8h9rA _5LkXAHO6Ee2vxNtY-8h9rA" incoming="_YkKR4HO4Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YkFZYXO4Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YkFZYHO4Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YkFZYnO4Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_J_GQgHO5Ee2vxNtY-8h9rA" text="Na polje koje govori o oceni 1, bice vezana skripta koja uvecava candadateNotRecommended za 2, &#xD;&#xA;Na polje koje govori o proceni ne preporucujem, bice vezana skripta koja uvecava candadateNotRecommended za 1&#xD;&#xA;&#xD;&#xA;Izabrati da se pojavi samo izabranim intervjuerima&#xD;&#xA; &#xD;&#xA;"/>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_GuZNYHO8Ee2vxNtY-8h9rA" name="Company HR Boss" actor="_CvGZMHOvEe2vxNtY-8h9rA">
        <elements xmi:type="process:Task" xmi:id="_EiI8wHOyEe2vxNtY-8h9rA" name="Choose interview team (Company HR Boss)" outgoing="_hJySoHOyEe2vxNtY-8h9rA" incoming="_DdN8EHOyEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_DdJDknOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_DdJDkXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_DdJDk3OyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_DdJDlHOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_DdJDlXOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_DdJDlnOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_DdJDmHOyEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_DdJDl3OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_EiJj2XOyEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhw4VGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_EiJj2HOyEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_EiJj23OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_A_vNAHOyEe2vxNtY-8h9rA" name="OrganizeInterview" outgoing="_DdN8EHOyEe2vxNtY-8h9rA _D2VmsHOyEe2vxNtY-8h9rA" incoming="_aGHewHO2Ee2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_A_vNAnOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_A_vNAXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_A_vNA3OyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_hJuBMHOyEe2vxNtY-8h9rA" name="Merge" outgoing="_qJxscHOyEe2vxNtY-8h9rA" incoming="_hJySoHOyEe2vxNtY-8h9rA _jwjgkHOyEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hJuoQHOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hJuBMXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hJuoQXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_r6ussHOyEe2vxNtY-8h9rA" name="Choose dates" outgoing="_6_cCAHOyEe2vxNtY-8h9rA" incoming="_dH2U8HO3Ee2vxNtY-8h9rA" useCardinality="true" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_qJsz8XOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_qJsz8HOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_qJsz8nOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_qJsz83OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_qJsz9HOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_qJsz9XOyEe2vxNtY-8h9rA" name="2" content="2" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_qJsz93OyEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_qJsz9nOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_r6v60XOyEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhxIVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_r6v60HOyEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_r6v603OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dHw1YHO3Ee2vxNtY-8h9rA" name="NotAcceptedDate" outgoing="_dH2U8HO3Ee2vxNtY-8h9rA" incoming="_qJxscHOyEe2vxNtY-8h9rA _y0SJAHOzEe2vxNtY-8h9rA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dHxccXO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dHxccHO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dHxccnO3Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_d4I3gHO5Ee2vxNtY-8h9rA" name="Company HR Boss Final Decision" outgoing="_L2yVcHO6Ee2vxNtY-8h9rA" incoming="_dfu-kHO5Ee2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_dfqtIXO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_dfqtIHO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_dfqtInO5Ee2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_dfqtI3O5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_dfqtJHO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_dfqtJXO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_dfqtJ3O5Ee2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_dfqtJnO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_d4JemXO5Ee2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhxYVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_d4JemHO5Ee2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_d4Jem3O5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_DX6PMHO7Ee2vxNtY-8h9rA" name="PremiumDepartment Boss Lane" actor="_MEDf8HO7Ee2vxNtY-8h9rA">
        <elements xmi:type="process:Task" xmi:id="_QGmwYHOwEe2vxNtY-8h9rA" name="Choose Employee" outgoing="_ZVPqMHOwEe2vxNtY-8h9rA" incoming="_xj9KIIU5Ee2xlJGGUNPD4A" actor="_t3zHQHO7Ee2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_PjkUwnOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_PjkUwXOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_PjkUw3OwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_qGi5MIVAEe2XGcS64ODCIQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_qGi5MYVAEe2XGcS64ODCIQ" name="chosenPremiumDeptEmployeeId" content="chosenPremiumDeptEmployeeId" type="TYPE_VARIABLE" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:Data" xmi:id="_rKpagIVAEe2XGcS64ODCIQ" name="chosenPremiumDeptEmployeeId" dataType="_rZ0U_nOuEe2vxNtY-8h9rA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_qGi5MoVAEe2XGcS64ODCIQ" name="selectedEmployeeId()" content="selectedEmployeeId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_ub-oYIVAEe2XGcS64ODCIQ" name="selectedEmployeeId" type="INTEGER">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_ub-oYYVAEe2XGcS64ODCIQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_qGi5M4VAEe2XGcS64ODCIQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_PjkUxHOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_PjkUxXOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_PjkUxnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_PjkUyHOwEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_PjkUx3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QGnXc3OwEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_4F5XsIU6Ee2xlJGGUNPD4A" name="SelectEmployeeForm" content="e0f61571-ac0f-4e2c-a486-b36e2f254870" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QGnXcnOwEe2vxNtY-8h9rA">
            <inputs xmi:type="process:ContractInput" xmi:id="_oIppIIVAEe2XGcS64ODCIQ" name="selectedEmployeeId" type="INTEGER">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_oIppIYVAEe2XGcS64ODCIQ"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QGnXdXOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Uhq7kHOyEe2vxNtY-8h9rA" name="Choose interview team (PremiumDep Boss)" outgoing="_jwjgkHOyEe2vxNtY-8h9rA" incoming="_D2VmsHOyEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D2QHIHOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D2PgEXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D2QHIXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D2QHInOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D2QHI3OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D2QHJHOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D2QHJnOyEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D2QHJXOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Uhq7mnOyEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhxoVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Uhq7mXOyEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Uhq7nHOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_nlxpMHOzEe2vxNtY-8h9rA" name="Accept selected dates" outgoing="_oaqp0HOzEe2vxNtY-8h9rA" incoming="_6_cCAHOyEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6_XwkXOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6_XwkHOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6_XwknOyEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6_Xwk3OyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6_XwlHOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6_XwlXOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6_Xwl3OyEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6_XwlnOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_nlyQSXOzEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhx4VGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_nlyQSHOzEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_nlyQS3OzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_01Tr8HO7Ee2vxNtY-8h9rA" name="ChosenPremiumDept Employee Lane" actor="_t3zHQHO7Ee2vxNtY-8h9rA">
        <elements xmi:type="process:Task" xmi:id="_Zu1O4HOwEe2vxNtY-8h9rA" name="Choose 3 companies" outgoing="_XuXkQHO2Ee2vxNtY-8h9rA" incoming="_ZVPqMHOwEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZVKKoXOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZVKKoHOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZVKKonOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_DB9mMIVHEe2XGcS64ODCIQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_DB9mMYVHEe2XGcS64ODCIQ" name="listOfSelectedCompanies" content="listOfSelectedCompanies" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:Data" xmi:id="_Kc5GsIVHEe2XGcS64ODCIQ" name="listOfSelectedCompanies" multiple="true" dataType="_rZ0U_nOuEe2vxNtY-8h9rA"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_DB9mMoVHEe2XGcS64ODCIQ" name="ids" content="ids" type="TYPE_CONTRACT_INPUT" returnType="java.util.List">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_K7JwAIVHEe2XGcS64ODCIQ" name="ids" type="INTEGER" multiple="true">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_K7JwAYVHEe2XGcS64ODCIQ"/>
              </referencedElements>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_DB9mM4VHEe2XGcS64ODCIQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZVKKo3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZVKKpHOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZVKKpXOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZVKKp3OwEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZVKKpnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Zu1O6nOwEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_hilpMIVCEe2XGcS64ODCIQ" name="SelectCompaniesForm" content="8e28e138-5e16-45b8-81e1-ec5985770851" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <filters xmi:type="process:ActorFilter" xmi:id="_927dcHO7Ee2vxNtY-8h9rA" name="chosenPremiumDeptEmployee" definitionId="bonita-actorfilter-single-user" definitionVersion="1.0.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_927dcXO7Ee2vxNtY-8h9rA" definitionId="bonita-actorfilter-single-user" version="1.0.0">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_927dcnO7Ee2vxNtY-8h9rA" key="userId">
                <expression xmi:type="expression:Expression" xmi:id="_927dc3O7Ee2vxNtY-8h9rA" name="userId()" content="return chosenPremiumDeptEmployeeId" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_927ddHO7Ee2vxNtY-8h9rA" name="chosenPremiumDeptEmployeeId" dataType="_rZ0U_nOuEe2vxNtY-8h9rA"/>
                </expression>
              </parameters>
            </configuration>
          </filters>
          <contract xmi:type="process:Contract" xmi:id="_Zu1O6XOwEe2vxNtY-8h9rA">
            <inputs xmi:type="process:ContractInput" xmi:id="_bfooQIVCEe2XGcS64ODCIQ" name="ids" type="INTEGER" multiple="true">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_bfooQYVCEe2XGcS64ODCIQ"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_0rwLEIVFEe2XGcS64ODCIQ" expression="boolean isSame = (ids[0] == ids[1] || ids[0] == ids[2] || ids[2] == ids[1]);&#xD;&#xA;if(ids.size() &lt; 3 &amp;&amp; isSame){&#xD;&#xA;&#x9;return false;&#xD;&#xA;}else{&#xD;&#xA;&#x9;return true;&#xD;&#xA;}" errorMessage="You cannot choose same company multiple times." name="sameCompanyCheck">
              <inputNames>ids</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Zu1O7HOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_4Pc4kHOwEe2vxNtY-8h9rA" name="Review CV and cover letter" outgoing="_61r7AHOwEe2vxNtY-8h9rA" incoming="_35z_wHOwEe2vxNtY-8h9rA" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_35vuUnOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_35vuUXOwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_35vuU3OwEe2vxNtY-8h9rA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_35vuVHOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_35vuVXOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_35vuVnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_35vuWHOwEe2vxNtY-8h9rA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_35vuV3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_4PdfqXOwEe2vxNtY-8h9rA">
            <targetForm xmi:type="expression:Expression" xmi:id="_lzUhyIVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_4PdfqHOwEe2vxNtY-8h9rA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_4Pdfq3OwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_ANDdUIVBEe2XGcS64ODCIQ" name="chosenPremiumDeptEmployee" definitionId="bonita-actorfilter-single-user" definitionVersion="1.0.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_ANDdUYVBEe2XGcS64ODCIQ" definitionId="bonita-actorfilter-single-user" version="1.0.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_ANDdUoVBEe2XGcS64ODCIQ" key="userId">
              <expression xmi:type="expression:Expression" xmi:id="_ANDdU4VBEe2XGcS64ODCIQ" name="userId()" content="new Long(chosenPremiumDeptEmployeeId)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long" returnTypeFixed="true">
                <referencedElements xmi:type="process:Data" xmi:id="_ANDdVIVBEe2XGcS64ODCIQ" name="chosenPremiumDeptEmployeeId" dataType="_rZ0U_nOuEe2vxNtY-8h9rA"/>
              </expression>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <data xmi:type="process:Data" xmi:id="_bVmN0HOvEe2vxNtY-8h9rA" name="areTermsAccepted" dataType="_rZ0U_HOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_bVmN0XOvEe2vxNtY-8h9rA" name="false" content="false" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_AaeZQHOxEe2vxNtY-8h9rA" name="isCVAndCoverLetterApproved" dataType="_rZ0U_HOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_AaeZQXOxEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_vCt74HOzEe2vxNtY-8h9rA" name="areDatesAccepted" dataType="_rZ0U_HOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_vCt74XOzEe2vxNtY-8h9rA" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_0uOQsHO0Ee2vxNtY-8h9rA" name="chosenDate" dataType="_rZ0VAnOuEe2vxNtY-8h9rA" className="java.util.Date">
        <defaultValue xmi:type="expression:Expression" xmi:id="_0uOQsXO0Ee2vxNtY-8h9rA" name="init_chosenDate()" content="return null" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.Date"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_IcWyUIVHEe2XGcS64ODCIQ" name="listOfSelectedCompanies" multiple="true" dataType="_rZ0U_nOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_IcWyUYVHEe2XGcS64ODCIQ" name="init_()" content="return new ArrayList()" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:JavaObjectData" xmi:id="_MfIZwHO4Ee2vxNtY-8h9rA" name="listOfInterviewers" dataType="_rZ0VAnOuEe2vxNtY-8h9rA" className="java.util.List">
        <defaultValue xmi:type="expression:Expression" xmi:id="_MfIZwXO4Ee2vxNtY-8h9rA" content="" returnType="java.util.List"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_g_FPwHO4Ee2vxNtY-8h9rA" name="candidateNotRecommended" dataType="_rZ0U_nOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_g_FPwXO4Ee2vxNtY-8h9rA" name="0" content="0" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_zo5OEHO5Ee2vxNtY-8h9rA" name="isCandidateApprovedByHRBoss" dataType="_rZ0U_HOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_zo5OEXO5Ee2vxNtY-8h9rA" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_niubkHO7Ee2vxNtY-8h9rA" name="chosenPremiumDeptEmployeeId" dataType="_rZ0U_nOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_niubkXO7Ee2vxNtY-8h9rA" content="" returnType="java.lang.Integer"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_v2BosIU5Ee2xlJGGUNPD4A" name="candidateInitiator" dataType="_rZ0VBHOuEe2vxNtY-8h9rA" className="com.company.model.CandidateRegistrationRequest">
        <defaultValue xmi:type="expression:Expression" xmi:id="_v2BosYU5Ee2xlJGGUNPD4A" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_1uFy0IU6Ee2xlJGGUNPD4A" name="test" dataType="_rZ0VAXOuEe2vxNtY-8h9rA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1uFy0YU6Ee2xlJGGUNPD4A" name="AAAAA" content="AAAAA"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_rZ0U5HOuEe2vxNtY-8h9rA">
        <targetForm xmi:type="expression:Expression" xmi:id="_lzUhyYVGEe2XGcS64ODCIQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_rZ0U5nOuEe2vxNtY-8h9rA">
        <targetForm xmi:type="expression:Expression" xmi:id="_rZ0U53OuEe2vxNtY-8h9rA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rZ0U6HOuEe2vxNtY-8h9rA" target="_rZ0U13OuEe2vxNtY-8h9rA" source="_rZ0U03OuEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rZ0U6XOuEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_rZ0U6nOuEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cCYbUHOvEe2vxNtY-8h9rA" target="_dUu0AHOvEe2vxNtY-8h9rA" source="_rZ0U13OuEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cCZCYHOvEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_cCZCYXOvEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_k-mvcHOvEe2vxNtY-8h9rA" name="termsNotAccepted" target="_k-fasHOvEe2vxNtY-8h9rA" source="_dUu0AHOvEe2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_k-mvcXOvEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_k-mvcnOvEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_mSeLEHOvEe2vxNtY-8h9rA" name="termsAccepted" target="_AAH1AHOwEe2vxNtY-8h9rA" source="_dUu0AHOvEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_mSeyIHOvEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_mSeyIXOvEe2vxNtY-8h9rA" name="areTermsAccepted()" content="return areTermsAccepted" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_tpMhAHOvEe2vxNtY-8h9rA" name="areTermsAccepted" dataType="_rZ0U_HOuEe2vxNtY-8h9rA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_PjrCcHOwEe2vxNtY-8h9rA" target="_xjWtMIU5Ee2xlJGGUNPD4A" source="_AAH1AHOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_PjrCcXOwEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_PjrCcnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZVPqMHOwEe2vxNtY-8h9rA" target="_Zu1O4HOwEe2vxNtY-8h9rA" source="_QGmwYHOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZVPqMXOwEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZVPqMnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xBZWcHOwEe2vxNtY-8h9rA" target="_zAT6MHOwEe2vxNtY-8h9rA" source="_k-KOEHOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xBZ9gHOwEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_xBZ9gXOwEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_35z_wHOwEe2vxNtY-8h9rA" target="_4Pc4kHOwEe2vxNtY-8h9rA" source="_zAT6MHOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_35z_wXOwEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_35z_wnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_61r7AHOwEe2vxNtY-8h9rA" target="_Bsc-gHOxEe2vxNtY-8h9rA" source="_4Pc4kHOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_61r7AXOwEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_61r7AnOwEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BsmvgHOxEe2vxNtY-8h9rA" name="CVAndCoverLetterNotApproved" target="_zAT6MHOwEe2vxNtY-8h9rA" source="_Bsc-gHOxEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BsmvgXOxEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_BsmvgnOxEe2vxNtY-8h9rA" name="isCVAndCoverLetterApproved()" content="return isCVAndCoverLetterApproved == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_QQRNQHOxEe2vxNtY-8h9rA" name="isCVAndCoverLetterApproved" dataType="_rZ0U_HOuEe2vxNtY-8h9rA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A_y3YHOyEe2vxNtY-8h9rA" name="CVAndCoverLetterApproved" target="_aGAxEHO2Ee2vxNtY-8h9rA" source="_Bsc-gHOxEe2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A_y3YXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_A_y3YnOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DdN8EHOyEe2vxNtY-8h9rA" target="_EiI8wHOyEe2vxNtY-8h9rA" source="_A_vNAHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DdN8EXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_DdN8EnOyEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D2VmsHOyEe2vxNtY-8h9rA" target="_Uhq7kHOyEe2vxNtY-8h9rA" source="_A_vNAHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D2VmsXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D2VmsnOyEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hJySoHOyEe2vxNtY-8h9rA" target="_hJuBMHOyEe2vxNtY-8h9rA" source="_EiI8wHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hJySoXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hJySonOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jwjgkHOyEe2vxNtY-8h9rA" target="_hJuBMHOyEe2vxNtY-8h9rA" source="_Uhq7kHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jwjgkXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_jwjgknOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qJxscHOyEe2vxNtY-8h9rA" target="_dHw1YHO3Ee2vxNtY-8h9rA" source="_hJuBMHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qJxscXOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_qJxscnOyEe2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6_cCAHOyEe2vxNtY-8h9rA" target="_nlxpMHOzEe2vxNtY-8h9rA" source="_r6ussHOyEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6_cpEHOyEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_6_cpEXOyEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oaqp0HOzEe2vxNtY-8h9rA" target="_0yh-YHOzEe2vxNtY-8h9rA" source="_nlxpMHOzEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oaqp0XOzEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_oaqp0nOzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_y0SJAHOzEe2vxNtY-8h9rA" name="DatesNotAccepted" target="_dHw1YHO3Ee2vxNtY-8h9rA" source="_0yh-YHOzEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_y0SJAXOzEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_y0SJAnOzEe2vxNtY-8h9rA" name="areDatesAccepted()" content="return areDatesAccepted == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_5KxJ8HOzEe2vxNtY-8h9rA" name="areDatesAccepted" dataType="_rZ0U_HOuEe2vxNtY-8h9rA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8JVz4HOzEe2vxNtY-8h9rA" name="DatesAccepted" target="_h3HOgHO5Ee2vxNtY-8h9rA" source="_0yh-YHOzEe2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8JVz4XOzEe2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_8JVz4nOzEe2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KDT0YHO0Ee2vxNtY-8h9rA" target="_KWPXcHO0Ee2vxNtY-8h9rA" source="_h3HOgHO5Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KDT0YXO0Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_KDT0YnO0Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1v1esHO0Ee2vxNtY-8h9rA" target="_7hmpAHO0Ee2vxNtY-8h9rA" source="_KWPXcHO0Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1v1esXO0Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_1v1esnO0Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__k108HO0Ee2vxNtY-8h9rA" name="declineInterview" target="_A3E44HO1Ee2vxNtY-8h9rA" source="_7hmpAHO0Ee2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__k2cAHO0Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="__k2cAXO0Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A3K_gHO1Ee2vxNtY-8h9rA" target="__kwVYHO0Ee2vxNtY-8h9rA" source="_A3E44HO1Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A3K_gXO1Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_A3K_gnO1Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CxjBgHO1Ee2vxNtY-8h9rA" target="_gqki4HO5Ee2vxNtY-8h9rA" source="_A3E44HO1Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CxjokHO1Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_CxjokXO1Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_nM3IAHO1Ee2vxNtY-8h9rA" name="acceptedInterview" target="_ovaYgHO4Ee2vxNtY-8h9rA" source="_7hmpAHO0Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_nM3IAXO1Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_nM3IAnO1Ee2vxNtY-8h9rA" name="acceptedInterview()" content="return chosenDate.equals(null) == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:JavaObjectData" xmi:id="_50xzcHO3Ee2vxNtY-8h9rA" name="chosenDate" dataType="_rZ0VAnOuEe2vxNtY-8h9rA" className="java.util.Date"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ruUhAHO1Ee2vxNtY-8h9rA" target="_ruQ2oHO1Ee2vxNtY-8h9rA" source="__kwVYHO0Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ruVIEHO1Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ruVIEXO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_sLlr0HO1Ee2vxNtY-8h9rA" target="_ruQ2oHO1Ee2vxNtY-8h9rA" source="_gqki4HO5Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_sLmS4HO1Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_sLmS4XO1Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XuXkQHO2Ee2vxNtY-8h9rA" target="_k-KOEHOwEe2vxNtY-8h9rA" source="_Zu1O4HOwEe2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XuXkQXO2Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_XuXkQnO2Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aGHewHO2Ee2vxNtY-8h9rA" target="_A_vNAHOyEe2vxNtY-8h9rA" source="_aGAxEHO2Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aGHewXO2Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_aGHewnO2Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_gv85gHO2Ee2vxNtY-8h9rA" name="anotherCompany" target="_aGAxEHO2Ee2vxNtY-8h9rA" source="_sKo0IHO2Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_gv85gXO2Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_gv85gnO2Ee2vxNtY-8h9rA" name="listOfSelectedCompanies()" content="return listOfSelectedCompanies.size()>1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:JavaObjectData" xmi:id="_slEJgHO6Ee2vxNtY-8h9rA" name="listOfSelectedCompanies" dataType="_rZ0VAnOuEe2vxNtY-8h9rA" className="java.util.List"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_syHq4HO2Ee2vxNtY-8h9rA" target="_sKo0IHO2Ee2vxNtY-8h9rA" source="_ruQ2oHO1Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_syHq4XO2Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_syHq4nO2Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HUJ_IHO3Ee2vxNtY-8h9rA" name="noOtherCompany" target="_HUFGoHO3Ee2vxNtY-8h9rA" source="_sKo0IHO2Ee2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HUJ_IXO3Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_HUJ_InO3Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dH2U8HO3Ee2vxNtY-8h9rA" target="_r6ussHOyEe2vxNtY-8h9rA" source="_dHw1YHO3Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dH2U8XO3Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dH2U8nO3Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YkKR4HO4Ee2vxNtY-8h9rA" target="_ceq_oHO4Ee2vxNtY-8h9rA" source="_ovaYgHO4Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YkK48HO4Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_YkK48XO4Ee2vxNtY-8h9rA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_dfu-kHO5Ee2vxNtY-8h9rA" name="CandidateAccepted" target="_d4I3gHO5Ee2vxNtY-8h9rA" source="_ceq_oHO4Ee2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_dfvloHO5Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_dfvloXO5Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_A8-6UHO6Ee2vxNtY-8h9rA" target="_Nhb5YHO6Ee2vxNtY-8h9rA" source="_5LX_MHO5Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_A8_hYHO6Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_A8_hYXO6Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L2yVcHO6Ee2vxNtY-8h9rA" target="_5LX_MHO5Ee2vxNtY-8h9rA" source="_d4I3gHO5Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L2yVcXO6Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_L2yVcnO6Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_NhfjwHO6Ee2vxNtY-8h9rA" name="SuccessfulInterview" target="_HUFGoHO3Ee2vxNtY-8h9rA" source="_Nhb5YHO6Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_NhfjwXO6Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_NhfjwnO6Ee2vxNtY-8h9rA" name="isCandidateApprovedByHRBoss()" content="return isCandidateApprovedByHRBoss" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_gEm5oHO6Ee2vxNtY-8h9rA" name="isCandidateApprovedByHRBoss" dataType="_rZ0U_HOuEe2vxNtY-8h9rA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wN54cHO6Ee2vxNtY-8h9rA" name="NotSuccessfulInterview" target="_sKo0IHO2Ee2vxNtY-8h9rA" source="_Nhb5YHO6Ee2vxNtY-8h9rA" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wN54cXO6Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_wN54cnO6Ee2vxNtY-8h9rA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5LkXAHO6Ee2vxNtY-8h9rA" name="CandidateRejected" target="_sKo0IHO2Ee2vxNtY-8h9rA" source="_ceq_oHO4Ee2vxNtY-8h9rA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5Lk-EHO6Ee2vxNtY-8h9rA"/>
        <condition xmi:type="expression:Expression" xmi:id="_5Lk-EXO6Ee2vxNtY-8h9rA" name="candidateNotRecommended()" content="return candidateNotRecommended > 1" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_7U3l0HO6Ee2vxNtY-8h9rA" name="candidateNotRecommended" dataType="_rZ0U_nOuEe2vxNtY-8h9rA"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xj9KIIU5Ee2xlJGGUNPD4A" target="_QGmwYHOwEe2vxNtY-8h9rA" source="_xjWtMIU5Ee2xlJGGUNPD4A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xj9xMIU5Ee2xlJGGUNPD4A"/>
        <condition xmi:type="expression:Expression" xmi:id="_xj9xMYU5Ee2xlJGGUNPD4A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="__4bHAHOuEe2vxNtY-8h9rA" name="Candidate" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_CvGZMHOvEe2vxNtY-8h9rA" name="Company HR Boss"/>
      <actors xmi:type="process:Actor" xmi:id="_MEDf8HO7Ee2vxNtY-8h9rA" name="PremiumDepartment Boss"/>
      <actors xmi:type="process:Actor" xmi:id="_t3zHQHO7Ee2vxNtY-8h9rA" name="ChosenPremiumDeptEmployee"/>
      <actors xmi:type="process:Actor" xmi:id="_xlymgHO8Ee2vxNtY-8h9rA" name="Interviewers"/>
      <contract xmi:type="process:Contract" xmi:id="_rZ0U7HOuEe2vxNtY-8h9rA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rZ0U7XOuEe2vxNtY-8h9rA">
        <name xmi:type="expression:Expression" xmi:id="_rZ0U7nOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rZ0U73OuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rZ0U8HOuEe2vxNtY-8h9rA">
        <name xmi:type="expression:Expression" xmi:id="_rZ0U8XOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rZ0U8nOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rZ0U83OuEe2vxNtY-8h9rA">
        <name xmi:type="expression:Expression" xmi:id="_rZ0U9HOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rZ0U9XOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rZ0U9nOuEe2vxNtY-8h9rA">
        <name xmi:type="expression:Expression" xmi:id="_rZ0U93OuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rZ0U-HOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_rZ0U-XOuEe2vxNtY-8h9rA">
        <name xmi:type="expression:Expression" xmi:id="_rZ0U-nOuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_rZ0U-3OuEe2vxNtY-8h9rA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_rZ0U_HOuEe2vxNtY-8h9rA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_rZ0U_XOuEe2vxNtY-8h9rA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_rZ0U_nOuEe2vxNtY-8h9rA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_rZ0U_3OuEe2vxNtY-8h9rA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_rZ0VAHOuEe2vxNtY-8h9rA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_rZ0VAXOuEe2vxNtY-8h9rA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_rZ0VAnOuEe2vxNtY-8h9rA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_rZ0VA3OuEe2vxNtY-8h9rA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_rZ0VBHOuEe2vxNtY-8h9rA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_rZ0VBXOuEe2vxNtY-8h9rA" type="Process" element="_rZ0U0HOuEe2vxNtY-8h9rA" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_rZ0VBnOuEe2vxNtY-8h9rA" type="2007" element="_rZ0U0XOuEe2vxNtY-8h9rA">
      <children xmi:type="notation:DecorationNode" xmi:id="_rZ0VB3OuEe2vxNtY-8h9rA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_rZ0VCHOuEe2vxNtY-8h9rA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_rZ0VCXOuEe2vxNtY-8h9rA" type="3007" element="_rZ0U0nOuEe2vxNtY-8h9rA">
          <children xmi:type="notation:DecorationNode" xmi:id="_rZ0VCnOuEe2vxNtY-8h9rA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_rZ0VC3OuEe2vxNtY-8h9rA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_rZ0VDHOuEe2vxNtY-8h9rA" type="3005" element="_rZ0U13OuEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_rZ0VDXOuEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rZ0VDnOuEe2vxNtY-8h9rA" x="160" y="109" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rZ074HOuEe2vxNtY-8h9rA" type="3002" element="_rZ0U03OuEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rZ074XOuEe2vxNtY-8h9rA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rZ074nOuEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rZ0743OuEe2vxNtY-8h9rA" x="60" y="117"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dUvbEHOvEe2vxNtY-8h9rA" type="3008" element="_dUu0AHOvEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dUvbEnOvEe2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dUvbE3OvEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dUvbEXOvEe2vxNtY-8h9rA" x="319" y="111" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_k-hP4HOvEe2vxNtY-8h9rA" type="3003" element="_k-fasHOvEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_k-hP4nOvEe2vxNtY-8h9rA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_k-hP43OvEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k-hP4XOvEe2vxNtY-8h9rA" x="326" y="243"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AAIcHHOwEe2vxNtY-8h9rA" type="3005" element="_AAH1AHOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AAJDIHOwEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AAIcHXOwEe2vxNtY-8h9rA" x="498" y="114" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_k-K1IHOwEe2vxNtY-8h9rA" type="3027" element="_k-KOEHOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_k-K1InOwEe2vxNtY-8h9rA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_k-K1IXOwEe2vxNtY-8h9rA" x="927" y="107" width="164" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_zAT6PXOwEe2vxNtY-8h9rA" type="3005" element="_zAT6MHOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zAT6P3OwEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zAT6PnOwEe2vxNtY-8h9rA" x="1220" y="118" width="138" height="69"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_BsdlkXOxEe2vxNtY-8h9rA" type="3008" element="_Bsc-gHOxEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_BseMoHOxEe2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_BseMoXOxEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BsdlknOxEe2vxNtY-8h9rA" x="1554" y="132"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0yilc3OzEe2vxNtY-8h9rA" type="3008" element="_0yh-YHOzEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0yildXOzEe2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0yildnOzEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0yildHOzEe2vxNtY-8h9rA" x="2575" y="148" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_KWP-gHO0Ee2vxNtY-8h9rA" type="3005" element="_KWPXcHO0Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_KWP-gnO0Ee2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_KWP-gXO0Ee2vxNtY-8h9rA" x="2865" y="149" width="112" height="56"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7hnQE3O0Ee2vxNtY-8h9rA" type="3008" element="_7hmpAHO0Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_7hnQFXO0Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_7hnQFnO0Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7hnQFHO0Ee2vxNtY-8h9rA" x="3017" y="154" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__kw8cHO0Ee2vxNtY-8h9rA" type="3027" element="__kwVYHO0Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__kw8cnO0Ee2vxNtY-8h9rA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__kw8cXO0Ee2vxNtY-8h9rA" x="3208" y="68" width="156" height="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A3Ff8HO1Ee2vxNtY-8h9rA" type="3009" element="_A3E44HO1Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_A3Ff8nO1Ee2vxNtY-8h9rA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_A3Ff83O1Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A3Ff8XO1Ee2vxNtY-8h9rA" x="3150" y="154"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ruRdsHO1Ee2vxNtY-8h9rA" type="3009" element="_ruQ2oHO1Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ruRdsnO1Ee2vxNtY-8h9rA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ruRds3O1Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ruRdsXO1Ee2vxNtY-8h9rA" x="3397" y="158"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_aGBYIHO2Ee2vxNtY-8h9rA" type="3008" element="_aGAxEHO2Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_aGBYInO2Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_aGBYI3O2Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_aGBYIXO2Ee2vxNtY-8h9rA" x="1695" y="132"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_sKqCQHO2Ee2vxNtY-8h9rA" type="3008" element="_sKo0IHO2Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_sKqCQnO2Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_sKqCQ3O2Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_sKqCQXO2Ee2vxNtY-8h9rA" x="3473" y="158"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HUGUwHO3Ee2vxNtY-8h9rA" type="3003" element="_HUFGoHO3Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_HUGUwnO3Ee2vxNtY-8h9rA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_HUGUw3O3Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HUGUwXO3Ee2vxNtY-8h9rA" x="3747" y="165"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_gqlJ-HO5Ee2vxNtY-8h9rA" type="3027" element="_gqki4HO5Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_gqlJ-nO5Ee2vxNtY-8h9rA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_gqlJ-XO5Ee2vxNtY-8h9rA" x="3207" y="216" width="181" height="91"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_h3HOiXO5Ee2vxNtY-8h9rA" type="3027" element="_h3HOgHO5Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_h3H1kHO5Ee2vxNtY-8h9rA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h3HOinO5Ee2vxNtY-8h9rA" x="2713" y="146" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5LZNUHO5Ee2vxNtY-8h9rA" type="3027" element="_5LX_MHO5Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5LZ0YHO5Ee2vxNtY-8h9rA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5LZNUXO5Ee2vxNtY-8h9rA" x="3568" y="418" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_NhcgcnO6Ee2vxNtY-8h9rA" type="3008" element="_Nhb5YHO6Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_NhcgdHO6Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_NhcgdXO6Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Nhcgc3O6Ee2vxNtY-8h9rA" x="3623" y="307"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_xjgeMIU5Ee2xlJGGUNPD4A" type="3027" element="_xjWtMIU5Ee2xlJGGUNPD4A" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_xjhsUIU5Ee2xlJGGUNPD4A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xjgeMYU5Ee2xlJGGUNPD4A" x="540" y="483" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_rZ075HOuEe2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_rZ075XOuEe2vxNtY-8h9rA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_rZ075nOuEe2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_rZ0753OuEe2vxNtY-8h9rA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rZ076HOuEe2vxNtY-8h9rA" x="23" y="10" width="3887" height="603"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_DX8rcHO7Ee2vxNtY-8h9rA" type="3007" element="_DX6PMHO7Ee2vxNtY-8h9rA">
          <children xmi:type="notation:DecorationNode" xmi:id="_DX8rdXO7Ee2vxNtY-8h9rA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_DX8rdnO7Ee2vxNtY-8h9rA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_QGnXdnOwEe2vxNtY-8h9rA" type="3005" element="_QGmwYHOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QGnXeHOwEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QGnXd3OwEe2vxNtY-8h9rA" x="688" y="33" width="126" height="63"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Uhq7nXOyEe2vxNtY-8h9rA" type="3005" element="_Uhq7kHOyEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Uhq7n3OyEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Uhq7nnOyEe2vxNtY-8h9rA" x="2014" y="38" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_nly3UHOzEe2vxNtY-8h9rA" type="3005" element="_nlxpMHOzEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_nlzeYHOzEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nly3UXOzEe2vxNtY-8h9rA" x="2541" y="35" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_DX8rcXO7Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_DX8rcnO7Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_DX8rc3O7Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_DX8rd3O7Ee2vxNtY-8h9rA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_DX8rdHO7Ee2vxNtY-8h9rA" x="48" y="556" width="3887" height="256"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_01U6EHO7Ee2vxNtY-8h9rA" type="3007" element="_01Tr8HO7Ee2vxNtY-8h9rA">
          <children xmi:type="notation:DecorationNode" xmi:id="_01U6FXO7Ee2vxNtY-8h9rA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_01U6FnO7Ee2vxNtY-8h9rA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Zu118HOwEe2vxNtY-8h9rA" type="3005" element="_Zu1O4HOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Zu118nOwEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Zu118XOwEe2vxNtY-8h9rA" x="851" y="25" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_4PdfrHOwEe2vxNtY-8h9rA" type="3005" element="_4Pc4kHOwEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_4PdfrnOwEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_4PdfrXOwEe2vxNtY-8h9rA" x="1373" y="25" width="132" height="66"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_01U6EXO7Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_01U6EnO7Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_01U6E3O7Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_01U6F3O7Ee2vxNtY-8h9rA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_01U6FHO7Ee2vxNtY-8h9rA" x="48" y="1371" width="3887" height="201"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_GubCkHO8Ee2vxNtY-8h9rA" type="3007" element="_GuZNYHO8Ee2vxNtY-8h9rA">
          <children xmi:type="notation:DecorationNode" xmi:id="_GubpoHO8Ee2vxNtY-8h9rA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_GubpoXO8Ee2vxNtY-8h9rA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_EiJj3HOyEe2vxNtY-8h9rA" type="3005" element="_EiI8wHOyEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_EiKK4HOyEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_EiJj3XOyEe2vxNtY-8h9rA" x="2004" y="52" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_A_v0EHOyEe2vxNtY-8h9rA" type="3009" element="_A_vNAHOyEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_A_v0EnOyEe2vxNtY-8h9rA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_A_v0E3OyEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_A_v0EXOyEe2vxNtY-8h9rA" x="1895" y="170"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_hJuoQnOyEe2vxNtY-8h9rA" type="3009" element="_hJuBMHOyEe2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_hJvPUHOyEe2vxNtY-8h9rA" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_hJvPUXOyEe2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hJuoQ3OyEe2vxNtY-8h9rA" x="2219" y="151"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_r6v61HOyEe2vxNtY-8h9rA" type="3005" element="_r6ussHOyEe2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_r6v61nOyEe2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r6v61XOyEe2vxNtY-8h9rA" x="2447" y="148" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dHyqkHO3Ee2vxNtY-8h9rA" type="3008" element="_dHw1YHO3Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dHyqknO3Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dHyqk3O3Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dHyqkXO3Ee2vxNtY-8h9rA" x="2314" y="151"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_d4JenHO5Ee2vxNtY-8h9rA" type="3005" element="_d4I3gHO5Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_d4JennO5Ee2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_d4JenXO5Ee2vxNtY-8h9rA" x="3471" y="18" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_GubCkXO8Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_GubCknO8Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_GubCk3O8Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_GubponO8Ee2vxNtY-8h9rA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GubClHO8Ee2vxNtY-8h9rA" x="48" y="856" width="3887" height="259"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_5BeU8HO8Ee2vxNtY-8h9rA" type="3007" element="_5Bdt4HO8Ee2vxNtY-8h9rA">
          <children xmi:type="notation:DecorationNode" xmi:id="_5Be8AHO8Ee2vxNtY-8h9rA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_5Be8AXO8Ee2vxNtY-8h9rA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ovaYjXO4Ee2vxNtY-8h9rA" type="3005" element="_ovaYgHO4Ee2vxNtY-8h9rA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ovaYj3O4Ee2vxNtY-8h9rA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ovaYjnO4Ee2vxNtY-8h9rA" x="2998" y="124" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_cerms3O4Ee2vxNtY-8h9rA" type="3008" element="_ceq_oHO4Ee2vxNtY-8h9rA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_cermtXO4Ee2vxNtY-8h9rA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_cermtnO4Ee2vxNtY-8h9rA" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_cermtHO4Ee2vxNtY-8h9rA" x="3342" y="132" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_J_G3kHO5Ee2vxNtY-8h9rA" type="3015" element="_J_GQgHO5Ee2vxNtY-8h9rA">
              <children xmi:type="notation:DecorationNode" xmi:id="_J_G3lXO5Ee2vxNtY-8h9rA" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_J_G3kXO5Ee2vxNtY-8h9rA"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_J_G3knO5Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_J_G3k3O5Ee2vxNtY-8h9rA"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_J_G3lHO5Ee2vxNtY-8h9rA" x="2656" y="90" width="303" height="75"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_5BeU8XO8Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_5BeU8nO8Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_5BeU83O8Ee2vxNtY-8h9rA"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_5Be8AnO8Ee2vxNtY-8h9rA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5BeU9HO8Ee2vxNtY-8h9rA" x="48" y="1271" width="3887" height="300"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_rZ076XOuEe2vxNtY-8h9rA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_rZ076nOuEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_rZ0763OuEe2vxNtY-8h9rA"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_rZ077HOuEe2vxNtY-8h9rA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rZ077XOuEe2vxNtY-8h9rA" width="3910" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_rZ077nOuEe2vxNtY-8h9rA"/>
    <edges xmi:type="notation:Connector" xmi:id="_rZ0773OuEe2vxNtY-8h9rA" type="4001" element="_rZ0U6HOuEe2vxNtY-8h9rA" source="_rZ074HOuEe2vxNtY-8h9rA" target="_rZ0VDHOuEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rZ078HOuEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rZ078XOuEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rZ078nOuEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rZ0783OuEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cCaQgHOvEe2vxNtY-8h9rA" type="4001" element="_cCYbUHOvEe2vxNtY-8h9rA" source="_rZ0VDHOuEe2vxNtY-8h9rA" target="_dUvbEHOvEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cCa3kHOvEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cCa3kXOvEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cCaQgXOvEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cCaQgnOvEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_k-qZ0HOvEe2vxNtY-8h9rA" type="4001" element="_k-mvcHOvEe2vxNtY-8h9rA" source="_dUvbEHOvEe2vxNtY-8h9rA" target="_k-hP4HOvEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_k-qZ03OvEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_k-qZ1HOvEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_k-qZ0XOvEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_k-qZ0nOvEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_mSkRsHOvEe2vxNtY-8h9rA" type="4001" element="_mSeLEHOvEe2vxNtY-8h9rA" source="_dUvbEHOvEe2vxNtY-8h9rA" target="_AAIcHHOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_mSk4wHOvEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_mSk4wXOvEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_mSkRsXOvEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_mSkRsnOvEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_PjrpgHOwEe2vxNtY-8h9rA" type="4001" element="_PjrCcHOwEe2vxNtY-8h9rA" source="_AAIcHHOwEe2vxNtY-8h9rA" target="_xjgeMIU5Ee2xlJGGUNPD4A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Pjrpg3OwEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_PjrphHOwEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_PjrpgXOwEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_PjrpgnOwEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZVQRQHOwEe2vxNtY-8h9rA" type="4001" element="_ZVPqMHOwEe2vxNtY-8h9rA" source="_QGnXdnOwEe2vxNtY-8h9rA" target="_Zu118HOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZVQ4UHOwEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZVQ4UXOwEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZVQRQXOwEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZVQRQnOwEe2vxNtY-8h9rA" points="[19, 32, -131, -210]$[19, 233, -131, -9]$[100, 233, -50, -9]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xBakkHOwEe2vxNtY-8h9rA" type="4001" element="_xBZWcHOwEe2vxNtY-8h9rA" source="_k-K1IHOwEe2vxNtY-8h9rA" target="_zAT6PXOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xBakk3OwEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xBaklHOwEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xBakkXOwEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xBakknOwEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_350m0HOwEe2vxNtY-8h9rA" type="4001" element="_35z_wHOwEe2vxNtY-8h9rA" source="_zAT6PXOwEe2vxNtY-8h9rA" target="_4PdfrHOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_350m03OwEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_350m1HOwEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_350m0XOwEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_350m0nOwEe2vxNtY-8h9rA" points="[-2, 35, -152, -1242]$[-2, 1272, -152, -5]$[84, 1272, -66, -5]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_61siEHOwEe2vxNtY-8h9rA" type="4001" element="_61r7AHOwEe2vxNtY-8h9rA" source="_4PdfrHOwEe2vxNtY-8h9rA" target="_BsdlkXOxEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_61siE3OwEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_61siFHOwEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_61siEXOwEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_61siEnOwEe2vxNtY-8h9rA" points="[-68, -33, -138, 1243]$[-68, -1276, -138, 0]$[49, -1276, -21, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_61twMHOwEe2vxNtY-8h9rA" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BsnWkHOxEe2vxNtY-8h9rA" type="4001" element="_BsmvgHOxEe2vxNtY-8h9rA" source="_BsdlkXOxEe2vxNtY-8h9rA" target="_zAT6PXOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BsnWk3OxEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BsnWlHOxEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BsnWkXOxEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BsnWknOxEe2vxNtY-8h9rA" points="[0, -21, 286, -20]$[0, -67, 286, -66]$[-308, -67, -22, -66]$[-308, -35, -22, -34]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A_6MIHOyEe2vxNtY-8h9rA" type="4001" element="_A_y3YHOyEe2vxNtY-8h9rA" source="_BsdlkXOxEe2vxNtY-8h9rA" target="_aGBYIHO2Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A_6MI3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A_6MJHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A_6MIXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A_6MInOyEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DdOjIHOyEe2vxNtY-8h9rA" type="4001" element="_DdN8EHOyEe2vxNtY-8h9rA" source="_A_v0EHOyEe2vxNtY-8h9rA" target="_EiJj3HOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DdOjI3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DdOjJHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DdOjIXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DdOjInOyEe2vxNtY-8h9rA" points="[-3, -18, -166, 84]$[-3, -103, -166, -1]$[88, -103, -75, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D2WNwHOyEe2vxNtY-8h9rA" type="4001" element="_D2VmsHOyEe2vxNtY-8h9rA" source="_A_v0EHOyEe2vxNtY-8h9rA" target="_Uhq7nXOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D2W00HOyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D2W00XOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D2WNwXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D2WNwnOyEe2vxNtY-8h9rA" points="[-1, 20, -99, -155]$[-1, 149, -99, -26]$[98, 149, 0, -26]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_bVlfYHOyEe2vxNtY-8h9rA" id="(0.0,0.9857142857142858)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hJy5sHOyEe2vxNtY-8h9rA" type="4001" element="_hJySoHOyEe2vxNtY-8h9rA" source="_EiJj3HOyEe2vxNtY-8h9rA" target="_hJuoQnOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hJy5s3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hJy5tHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hJy5sXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hJy5snOyEe2vxNtY-8h9rA" points="[75, 3, -86, -80]$[160, 3, -1, -80]$[160, 63, -1, -20]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jwkHoHOyEe2vxNtY-8h9rA" type="4001" element="_jwjgkHOyEe2vxNtY-8h9rA" source="_Uhq7nXOyEe2vxNtY-8h9rA" target="_hJuoQnOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jwkHo3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jwkHpHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jwkHoXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jwkHonOyEe2vxNtY-8h9rA" points="[0, 7, -86, 232]$[83, 7, -3, 232]$[83, -207, -3, 18]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jwl80HOyEe2vxNtY-8h9rA" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qJyTgHOyEe2vxNtY-8h9rA" type="4001" element="_qJxscHOyEe2vxNtY-8h9rA" source="_hJuoQnOyEe2vxNtY-8h9rA" target="_dHyqkHO3Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qJyTg3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qJyThHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qJyTgXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qJyTgnOyEe2vxNtY-8h9rA" points="[22, 0, -58, 0]$[59, 0, -21, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6_dQIHOyEe2vxNtY-8h9rA" type="4001" element="_6_cCAHOyEe2vxNtY-8h9rA" source="_r6v61HOyEe2vxNtY-8h9rA" target="_nly3UHOzEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6_dQI3OyEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6_d3MHOyEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6_dQIXOyEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6_dQInOyEe2vxNtY-8h9rA" points="[6, 25, -98, -126]$[6, 148, -98, -3]$[44, 148, -60, -3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oaqp03OzEe2vxNtY-8h9rA" type="4001" element="_oaqp0HOzEe2vxNtY-8h9rA" source="_nly3UHOzEe2vxNtY-8h9rA" target="_0yilc3OzEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oaqp1nOzEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oarQ4HOzEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oaqp1HOzEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oaqp1XOzEe2vxNtY-8h9rA" points="[-2, -30, -40, 980]$[-2, -1016, -40, -6]$[23, -1016, -15, -6]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_y0SwEHOzEe2vxNtY-8h9rA" type="4001" element="_y0SJAHOzEe2vxNtY-8h9rA" source="_0yilc3OzEe2vxNtY-8h9rA" target="_dHyqkHO3Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_y0TXIHOzEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_y0TXIXOzEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_y0SwEXOzEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_y0SwEnOzEe2vxNtY-8h9rA" points="[-40, -11, 244, -841]$[-284, -11, 0, -841]$[-284, 831, 0, 1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_y0VMUHOzEe2vxNtY-8h9rA" id="(1.0,0.6744186046511628)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_d0KBUHO3Ee2vxNtY-8h9rA" id="(0.46511627906976744,0.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8JaFUHOzEe2vxNtY-8h9rA" type="4001" element="_8JVz4HOzEe2vxNtY-8h9rA" source="_0yilc3OzEe2vxNtY-8h9rA" target="_h3HOiXO5Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8JaFU3OzEe2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8JaFVHOzEe2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8JaFUXOzEe2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8JaFUnOzEe2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KDUbcHO0Ee2vxNtY-8h9rA" type="4001" element="_KDT0YHO0Ee2vxNtY-8h9rA" source="_h3HOiXO5Ee2vxNtY-8h9rA" target="_KWP-gHO0Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KDUbc3O0Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KDUbdHO0Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KDUbcXO0Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KDUbcnO0Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1v1es3O0Ee2vxNtY-8h9rA" type="4001" element="_1v1esHO0Ee2vxNtY-8h9rA" source="_KWP-gHO0Ee2vxNtY-8h9rA" target="_7hnQE3O0Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1v1etnO0Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1v1et3O0Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1v1etHO0Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1v1etXO0Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__k2cAnO0Ee2vxNtY-8h9rA" type="4001" element="__k108HO0Ee2vxNtY-8h9rA" source="_7hnQE3O0Ee2vxNtY-8h9rA" target="_A3Ff8HO1Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__k2cBXO0Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__k2cBnO0Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__k2cA3O0Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__k2cBHO0Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A3K_g3O1Ee2vxNtY-8h9rA" type="4001" element="_A3K_gHO1Ee2vxNtY-8h9rA" source="_A3Ff8HO1Ee2vxNtY-8h9rA" target="__kw8cHO0Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A3LmkHO1Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A3LmkXO1Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A3K_hHO1Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A3K_hXO1Ee2vxNtY-8h9rA" points="[0, -21, -120, 39]$[0, -60, -120, 0]$[42, -60, -78, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CxjoknO1Ee2vxNtY-8h9rA" type="4001" element="_CxjBgHO1Ee2vxNtY-8h9rA" source="_A3Ff8HO1Ee2vxNtY-8h9rA" target="_gqlJ-HO5Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CxjolXO1Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CxjolnO1Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Cxjok3O1Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CxjolHO1Ee2vxNtY-8h9rA" points="[0, 22, -132, -72]$[0, 93, -132, -1]$[42, 93, -90, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_nM7ZcHO1Ee2vxNtY-8h9rA" type="4001" element="_nM3IAHO1Ee2vxNtY-8h9rA" source="_7hnQE3O0Ee2vxNtY-8h9rA" target="_ovaYjXO4Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_nM7Zc3O1Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_nM7ZdHO1Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_nM7ZcXO1Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_nM7ZcnO1Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ruVIEnO1Ee2vxNtY-8h9rA" type="4001" element="_ruUhAHO1Ee2vxNtY-8h9rA" source="__kw8cHO0Ee2vxNtY-8h9rA" target="_ruRdsHO1Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ruVvIHO1Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ruVvIXO1Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ruVIE3O1Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ruVIFHO1Ee2vxNtY-8h9rA" points="[78, -1, -54, -73]$[131, -1, -1, -73]$[131, 52, -1, -20]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_sLmS4nO1Ee2vxNtY-8h9rA" type="4001" element="_sLlr0HO1Ee2vxNtY-8h9rA" source="_gqlJ-HO5Ee2vxNtY-8h9rA" target="_ruRdsHO1Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_sLm58nO1Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_sLm583O1Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_sLm58HO1Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_sLm58XO1Ee2vxNtY-8h9rA" points="[0, 0, -27, 55]$[29, 0, 2, 55]$[29, -48, 2, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sLovIHO1Ee2vxNtY-8h9rA" id="(1.0,0.34065934065934067)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_sLovIXO1Ee2vxNtY-8h9rA" id="(0.4186046511627907,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XuXkQ3O2Ee2vxNtY-8h9rA" type="4001" element="_XuXkQHO2Ee2vxNtY-8h9rA" source="_Zu118HOwEe2vxNtY-8h9rA" target="_k-K1IHOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XuYLUHO2Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XuYLUXO2Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XuXkRHO2Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XuXkRXO2Ee2vxNtY-8h9rA" points="[-52, -29, -44, 1252]$[-52, -1277, -44, 4]$[-24, -1277, -16, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XuYyYHO2Ee2vxNtY-8h9rA" id="(1.0,0.58)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_XuYyYXO2Ee2vxNtY-8h9rA" id="(0.0975609756097561,0.45121951219512196)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aGHew3O2Ee2vxNtY-8h9rA" type="4001" element="_aGHewHO2Ee2vxNtY-8h9rA" source="_aGBYIHO2Ee2vxNtY-8h9rA" target="_A_v0EHOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aGIF0HO2Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aGIF0XO2Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aGHexHO2Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aGHexXO2Ee2vxNtY-8h9rA" points="[-3, 18, -204, -1062]$[-3, 1079, -204, -1]$[179, 1079, -22, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_gv9gkHO2Ee2vxNtY-8h9rA" type="4001" element="_gv85gHO2Ee2vxNtY-8h9rA" source="_sKqCQHO2Ee2vxNtY-8h9rA" target="_aGBYIHO2Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_gv9gk3O2Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_gv9glHO2Ee2vxNtY-8h9rA" x="-4" y="16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_gv9gkXO2Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_gv9gknO2Ee2vxNtY-8h9rA" points="[-2, -6, 1778, 5]$[-2, -122, 1778, -111]$[-1759, -122, 21, -111]$[-1759, -12, 21, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_gv-usHO2Ee2vxNtY-8h9rA" id="(0.5348837209302325,0.13953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_syIR8HO2Ee2vxNtY-8h9rA" type="4001" element="_syHq4HO2Ee2vxNtY-8h9rA" source="_ruRdsHO1Ee2vxNtY-8h9rA" target="_sKqCQHO2Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_syIR83O2Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_syIR9HO2Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_syIR8XO2Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_syIR8nO2Ee2vxNtY-8h9rA" points="[-14, 5, -57, 13]$[36, -22, -7, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_syKHIHO2Ee2vxNtY-8h9rA" id="(1.0,0.6744186046511628)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HUPesHO3Ee2vxNtY-8h9rA" type="4001" element="_HUJ_IHO3Ee2vxNtY-8h9rA" source="_sKqCQHO2Ee2vxNtY-8h9rA" target="_HUGUwHO3Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HUQFwHO3Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HUQFwXO3Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HUPesXO3Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HUPesnO3Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dH2U83O3Ee2vxNtY-8h9rA" type="4001" element="_dH2U8HO3Ee2vxNtY-8h9rA" source="_dHyqkHO3Ee2vxNtY-8h9rA" target="_r6v61HOyEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dH28AHO3Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dH28AXO3Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dH2U9HO3Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dH2U9XO3Ee2vxNtY-8h9rA" points="[19, -2, -143, -3]$[112, -2, -50, -3]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YkLgAHO4Ee2vxNtY-8h9rA" type="4001" element="_YkKR4HO4Ee2vxNtY-8h9rA" source="_ovaYjXO4Ee2vxNtY-8h9rA" target="_cerms3O4Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YkLgA3O4Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YkLgBHO4Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YkLgAXO4Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YkLgAnO4Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_J_X9UHO5Ee2vxNtY-8h9rA" type="4003" element="_J_WIIHO5Ee2vxNtY-8h9rA" source="_J_G3kHO5Ee2vxNtY-8h9rA" target="_ovaYjXO4Ee2vxNtY-8h9rA">
      <styles xmi:type="notation:FontStyle" xmi:id="_J_X9UXO5Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_J_X9UnO5Ee2vxNtY-8h9rA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_dfyo8HO5Ee2vxNtY-8h9rA" type="4001" element="_dfu-kHO5Ee2vxNtY-8h9rA" source="_cerms3O4Ee2vxNtY-8h9rA" target="_d4JenHO5Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_dfzQAHO5Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_dfzQAXO5Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_dfyo8XO5Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_dfyo8nO5Ee2vxNtY-8h9rA" points="[-1, 20, -169, -175]$[-1, 194, -169, -1]$[108, 194, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_A8_hYnO6Ee2vxNtY-8h9rA" type="4001" element="_A8-6UHO6Ee2vxNtY-8h9rA" source="_5LZNUHO5Ee2vxNtY-8h9rA" target="_NhcgcnO6Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_A8_hZXO6Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_A8_hZnO6Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_A8_hY3O6Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_A8_hZHO6Ee2vxNtY-8h9rA" points="[-60, -25, -3, 90]$[-60, -63, -3, 52]$[-50, -63, 7, 52]$[-50, -100, 7, 15]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_A9AvgHO6Ee2vxNtY-8h9rA" id="(1.0,0.3246753246753247)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L2y8gHO6Ee2vxNtY-8h9rA" type="4001" element="_L2yVcHO6Ee2vxNtY-8h9rA" source="_d4JenHO5Ee2vxNtY-8h9rA" target="_5LZNUHO5Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L2y8g3O6Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L2y8hHO6Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L2y8gXO6Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L2y8gnO6Ee2vxNtY-8h9rA" points="[-62, -31, -45, 416]$[-62, -449, -45, -2]$[-23, -449, -6, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L20KoHO6Ee2vxNtY-8h9rA" id="(1.0,0.5166666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_L20KoXO6Ee2vxNtY-8h9rA" id="(0.03896103896103896,0.5194805194805194)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_NhgK0HO6Ee2vxNtY-8h9rA" type="4001" element="_NhfjwHO6Ee2vxNtY-8h9rA" source="_NhcgcnO6Ee2vxNtY-8h9rA" target="_HUGUwHO3Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_NhgK03O6Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_NhgK1HO6Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_NhgK0XO6Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_NhgK0nO6Ee2vxNtY-8h9rA" points="[19, -2, -99, 146]$[115, -2, -3, 146]$[115, -134, -3, 14]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wOSS8HO6Ee2vxNtY-8h9rA" type="4001" element="_wN54cHO6Ee2vxNtY-8h9rA" source="_NhcgcnO6Ee2vxNtY-8h9rA" target="_sKqCQHO2Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wOSS83O6Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wOSS9HO6Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wOSS8XO6Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wOSS8nO6Ee2vxNtY-8h9rA" points="[-10, -19, 162, 139]$[-10, -148, 162, 10]$[-160, -148, 12, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wOUIIHO6Ee2vxNtY-8h9rA" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5LpPgHO6Ee2vxNtY-8h9rA" type="4001" element="_5LkXAHO6Ee2vxNtY-8h9rA" source="_cerms3O4Ee2vxNtY-8h9rA" target="_sKqCQHO2Ee2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5Lp2knO6Ee2vxNtY-8h9rA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5Lp2k3O6Ee2vxNtY-8h9rA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5Lp2kHO6Ee2vxNtY-8h9rA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5Lp2kXO6Ee2vxNtY-8h9rA" points="[-23, -22, -254, 510]$[-23, -331, -254, 201]$[236, -331, 5, 201]$[236, -515, 5, 17]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5LrEsHO6Ee2vxNtY-8h9rA" id="(1.0,0.5348837209302325)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xj_mYIU5Ee2xlJGGUNPD4A" type="4001" element="_xj9KIIU5Ee2xlJGGUNPD4A" source="_xjgeMIU5Ee2xlJGGUNPD4A" target="_QGnXdnOwEe2vxNtY-8h9rA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xkANcIU5Ee2xlJGGUNPD4A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xkANcYU5Ee2xlJGGUNPD4A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xj_mYYU5Ee2xlJGGUNPD4A" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xj_mYoU5Ee2xlJGGUNPD4A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
